# Generated by Django 4.0.3 on 2023-09-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='season',
            field=models.ForeignKey(default='2023', on_delete=django.db.models.deletion.CASCADE, to='season.season'),
        ),
    ]
