# Generated by Django 4.0.3 on 2024-01-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0004_remove_field_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='coordinates',
            field=models.TextField(),
        ),
    ]
