"""
Django settings for djangoauthapi1 project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import ee

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_zk=9yl=ul!po@_z-)wq&x4=&!(ons2(pogyu52+f7f37v3j$y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.vercel.app', '.now.sh']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken', 
    'rest_framework_simplejwt',
    'account',
    'farms',
    'vegetation',
    'fields',
    'season',
    'fieldData',
    'modelsML'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'djangoauthapi1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoauthapi1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql', 
#         'NAME': 'fyp',
#         'USER': 'root',
#         'PASSWORD': '23rida',
#         'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
#         'PORT': '3306',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'fyp',
        'CLIENT': {
            'host': 'mongodb+srv://next-tailwind-amazona:behzadkhadim@cluster0.bpdqerm.mongodb.net/',
            'username': 'next-tailwind-amazona',
            'password': 'behzadkhadim',
        },
    }
}

# JWT Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ) 
  
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = os.path.join(BASE_DIR, 'static'),
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build', 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'account.User'

# Email Configuration
EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASS')
EMAIL_USE_TLS = True


# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=20),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    
    # 'AUTH_HEADER_TYPES': ('JWT',),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

}

PASSWORD_RESET_TIMEOUT=900          # 900 Sec = 15 Min

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3001",
    "http://127.0.0.1:8000",

]

CORS_ALLOW_CREDENTIALS = True

GEE_JSON_KEY_FILE = os.path.join(
    BASE_DIR,'djangoauthapi1\\booming-client-377818-25d48daff981.json')
     
    #   'djangoauthapi1\\booming-client-377818-25d48daff981.json')

# The service account email associated with the key
GEE_ACCOUNT = 'booming-client-377818@appspot.gserviceaccount.com'


# Initialize Earth Engine
credentials = ee.ServiceAccountCredentials(email=GEE_ACCOUNT, key_file=GEE_JSON_KEY_FILE)
ee.Initialize(credentials)

# The private key data from your JSON key file
GEE_PRIVATE_KEY = '''
-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC8/k7d9lAqrpRI\nyCjzatZkZ1MEHJ9LupbU4R1yb6tYjupELW22laF8lswMHyCK+NZZs5l3jPwCBROL\nMd2q6wZoLT6pUSk9VNshaEwDqB+7yngjE1BmwYTle+QlBSk4fCUolM4jKVATMo4l\ncpdk34+e4iy7xk9u6dYopHluNrQDpQ21Dsftk5aD6PptWDAXNOkbIkujjFQG3Gxp\nY+qfVzFph8QiZ21vuUC0uz1mGM75DKVaCr3+kjZnqQx+FSF6t/HpYldO7Ou4XfFu\n81dm29YpTQ81VfiI7/gcSof8jKe2PSvCI9xnUmdULjimDc14kwyncqRXrfqb5Dmr\nJ/UGJIV3AgMBAAECggEANaL48A6RJuPgCp3f3WFzUhBu44pZ/SyJ1QXEjS87EkmR\nG+NGsVxa9dh4NXJ6EmbXsqKBigfVl58oMkdnMTQ9X8CDeZsimJjmDd+jPyBuTSYD\nnXTESz1dwaE9GPKThcfZ5eABdsIpSyF8bQ1OAR9fi8iFyI7aCVDM6kDvg4N76FJo\n3LJ5jhnbjlPGyDtotJUMLlxrFYKXCIU5L09ohMGra+9Zj6pUUXDqYk/dulk8aWtM\nBUCh3+ZfF7SkjVKP0Ff7H2+lAgga1LkjoNlQExFA9M7d6ohHMypmTwv8R5gkULoJ\naiKTkVpAnm2TPaJU/Q8lu0yYWiYLY6wf42M8CnkY8QKBgQDsG4YUfl/9nbUD/4Vg\n07Qq3YPE7eEKaLCns7laZlKTI//sAcYzhG2byovQMj5lxyXaYVtxZdWRrVc8+x9J\n1dymBTBhwvcn83veP3eJnSFWKRM/FG3rvBH5/4i4xfaDbeUpq3ZeTtYpNjz68KOA\n8c0G1JguYXbthWSCqmvjQdc5sQKBgQDM6prma981jKv0OgcSWT8Jtz+o7zFKm3oD\nSU1wlZdBZFgVePlsyxeCYNUvAD1HmGeWqxNOKItwHVVL0eTq+f7ZTUq8G6AIJmn0\nDUnJh53NWIQnt0fA4wE/vSnRa9U3M+gUMwuH8BBAjrvudev5Fbj8AsK8nW0WWtYF\nHoSRXIHTpwKBgQCABiyd0CicjHcqw9K+vgxjcdmRXqs3yayAQqOusOz1e/+5KP0f\n0h7c6ucE7TmIVoPf9gpvYph7dVJoboJ4ts3997JUUDNUJmJ0EFXw+JKq9XrKKXmw\n6TmWJUktZ6pTebNY9PAqEvVtQ0uthe4ibPqPSZd7Dr497Kajc2UsxPa/AQKBgHGG\neBK4KI0uRgWkME7GCtqDH02kVpaS1GIFtlVtSsL7qKEcyHKxgXDF3NWROGH12U3r\nsWJXrAiM97htrHlRzxLscz8LvvlE7uY6hmqUK6ScKXsnWyVNnl+FmSlgqFtQ8n5e\nWUESiq55ZTyTMAxrMHTNwr1kKg98e52SbrdpnLN5AoGACQuQtRMs/mioJBRNoJBj\n85Bf9fSj6NMBumG2KC90hvL7FwzsrTt1lG+GkaGhbXNrAnKcy05KIizy+tRe1YQY\nUsmwDfuKcYronbAWt/hik+10pKL5xM2slurA8xI7dRPFxinLI8yPjc1ois9iMzls\nfm9ufs31Z+HhowqQHZE+V6M=\n-----END PRIVATE KEY-----\n
'''

