# Generated by Django 4.0.3 on 2024-01-31 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=100)),
                ('input', models.CharField(default='Some string', max_length=200)),
                ('start_month', models.CharField(default='Some string', max_length=200)),
                ('end_month', models.CharField(default='Some string', max_length=200)),
                ('job_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldscoordinates', models.TextField(default='default_string_value')),
                ('crop_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sowing_date', models.CharField(default='Some string', max_length=200)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.field')),
                ('jobs', models.ManyToManyField(blank=True, related_name='fields', to='fieldData.job')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='season.season')),
            ],
            options={
                'unique_together': {('field', 'season')},
            },
        ),
    ]
