# Generated by Django 4.0.3 on 2023-10-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldData', '0002_fielddata_fieldscoordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddata',
            name='crop_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
