# Generated by Django 4.0.3 on 2023-10-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldData', '0003_fielddata_crop_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=100)),
                ('job_name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='fielddata',
            name='job',
        ),
        migrations.AddField(
            model_name='fielddata',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='fields', to='fieldData.job'),
        ),
    ]
