# Generated by Django 4.0.3 on 2023-10-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fieldData', '0005_job_end_month_job_input_job_job_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_name',
        ),
    ]
