# Generated by Django 4.0.3 on 2024-01-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldData', '0006_remove_job_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddata',
            name='sowing_date',
            field=models.CharField(default='Some string', max_length=200),
        ),
    ]
