# Generated by Django 4.0.3 on 2024-01-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldData', '0008_alter_fielddata_fieldscoordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddata',
            name='fieldscoordinates',
            field=models.TextField(default='Some string'),
        ),
    ]
