# Generated by Django 4.0.3 on 2023-10-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='end_month',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='start_month',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='year',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
