# Generated by Django 4.0.3 on 2023-10-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_season_end_month_season_start_month_season_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='year',
        ),
    ]
