# Generated by Django 4.0.3 on 2023-10-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0004_alter_season_end_month_alter_season_start_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='end_month',
            field=models.CharField(default='Some string', max_length=200),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_month',
            field=models.CharField(default='Some string', max_length=200),
        ),
    ]
